// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/ducnv194023/shoppe_be_go/internal/controller"
	"github.com/ducnv194023/shoppe_be_go/internal/repo"
	"github.com/ducnv194023/shoppe_be_go/internal/services"
)

// Injectors from auth.wire.go:

func InitializeAuthHandler() (*controller.AuthController, error) {
	iUserRepo := repo.NewUserRepo()
	iotpRepo := repo.NewOTPRepo()
	iMailService := services.NewMailService()
	iAuthService := services.NewAuthService(iUserRepo, iotpRepo, iMailService)
	authController := controller.NewAuthController(iAuthService)
	return authController, nil
}
