// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/ducnv194023/shoppe_be_go/internal/controller"
	"github.com/ducnv194023/shoppe_be_go/internal/repo"
	"github.com/ducnv194023/shoppe_be_go/internal/services"
)

// Injectors from wire.go:

func InitializeUserHandler() (*controller.UserController, error) {
	iUserRepo := repo.NewUserRepo()
	iUserService := services.NewUserService(iUserRepo)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
